"""Name of the View used for testing (for reverse lookup)"""
with_target_object_view = "with_target_object_view"
no_object_view = "no_object_view"
template_tags = "test_template_tags_view"
middleware = "middleware_view"
