dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install:
  pip install -r mentions/requirements.txt

script:
  python manage.py makemigrations
  python manage.py migrate
  python runtests.py
