dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

addons:
  postgresql: "9.6"

services:
  - postgresql

install:
  - pip install -r mentions/requirements.txt
  - pip install psycopg2

before_script:
  - psql --version
  - psql -c 'create database djangowm_test;' -U postgres

script:
  - python runtests.py
