dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r mentions/requirements.txt
script:
- python runtests.py
notifications:
  slack:
    secure: tjV/NGqP6wNr/5JSZvEtt7uauYwvRRAfnkvKFx7J9bT9Q5yokVzAkj22knPlNh0TFH+RMlIItF1Lht1p/rCCT6RMkHWJJUbyvKuJrVSsZaaynhothmsK4vBVnRL2HLQhitNdLaa6VYgL8Gex/gyPlkfUadgj1862Ss5m521R/o+lq6QfiHfhRvKXEfblCzNWERELvFgIxt8dX4SVlvzlmGLpDCUkVxkI+inLsT48jIN1AVhKk2rJYOip3KVMuwmJqsMwrbGOdN2F2M3HwoEzLhKLKWQ9Ic+Ulq1TL+nEd1P/nw6+03aoVyFYYGGhoDrXj8dWt80Qpxj422WpSdEJCoKq3w7DRjcxAuR7MzRR5oj/+onb2/A0YVTf+IqAV5q23vfGYlKYGAGoXlngGW4IqATpzRSYXwcmwcZ5OyuITSXK67D7IORXzz4yBzdCt2Xoffg50wGur8sPDIGSzgB1MofViPU8wS7TNI5bCXeJLwVTqCSQqjyPwma67MfYqOF5h8X/t3A2yfImtfyRtxyjUkty/f6M6FHLCsMufPDcKSUE/WcOm2b2yN1lI+oz+TSxK+e6dzxeXOVRdVEDMnUjpUcZXqxABuCsFYTb/AkW3Kp0J0LqLweX91Z+lxM4TPuFeuW4sI7sZxxatlNMf4dRra5QPf6BTOaNqBovccjexqQ=
