# Generated by Django 4.0.8 on 2023-05-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0012_alter_hcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmention',
            name='has_been_read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
    ]
