# Generated by Django 6.0 on 2026-01-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentions", "0013_webmention_has_been_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hcard",
            name="avatar",
            field=models.URLField(
                blank=True,
                help_text="Link to their profile image.",
                max_length=500,
                null=True,
                verbose_name="avatar URL",
            ),
        ),
        migrations.AlterField(
            model_name="hcard",
            name="homepage",
            field=models.URLField(
                blank=True,
                help_text="Link to their homepage.",
                max_length=500,
                null=True,
                verbose_name="homepage URL",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingwebmentionstatus",
            name="source_url",
            field=models.URLField(
                help_text="The URL on your server where this mention originates.",
                max_length=500,
                verbose_name="source URL",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingwebmentionstatus",
            name="target_url",
            field=models.URLField(
                help_text="The URL that you mentioned.",
                max_length=500,
                verbose_name="target URL",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingwebmentionstatus",
            name="target_webmention_endpoint",
            field=models.URLField(
                blank=True,
                help_text="The endpoint URL to which we sent the webmention.",
                max_length=500,
                null=True,
                verbose_name="target webmention endpoint",
            ),
        ),
        migrations.AlterField(
            model_name="pendingincomingwebmention",
            name="sent_by",
            field=models.URLField(
                help_text="The origin of the webmention request.",
                max_length=500,
                verbose_name="sent by",
            ),
        ),
        migrations.AlterField(
            model_name="pendingincomingwebmention",
            name="source_url",
            field=models.URLField(
                help_text="The URL of the content that mentions your content.",
                max_length=500,
                verbose_name="source URL",
            ),
        ),
        migrations.AlterField(
            model_name="pendingincomingwebmention",
            name="target_url",
            field=models.URLField(
                help_text="The URL of the page on your server that is being mentioned.",
                max_length=500,
                verbose_name="target URL",
            ),
        ),
        migrations.AlterField(
            model_name="pendingoutgoingcontent",
            name="absolute_url",
            field=models.URLField(
                help_text="URL on our server where the content can be found.",
                max_length=500,
                unique=True,
                verbose_name="absolute URL",
            ),
        ),
        migrations.AlterField(
            model_name="simplemention",
            name="source_url",
            field=models.URLField(
                help_text="The URL that mentions our content.",
                max_length=500,
                verbose_name="source URL",
            ),
        ),
        migrations.AlterField(
            model_name="simplemention",
            name="target_url",
            field=models.URLField(
                help_text="Our URL that is mentioned.",
                max_length=500,
                verbose_name="target URL",
            ),
        ),
        migrations.AlterField(
            model_name="webmention",
            name="sent_by",
            field=models.URLField(
                blank=True,
                help_text="Source address of the HTTP request that sent this webmention.",
                max_length=500,
                verbose_name="sent by",
            ),
        ),
        migrations.AlterField(
            model_name="webmention",
            name="source_url",
            field=models.URLField(
                help_text="The URL that mentions our content.",
                max_length=500,
                verbose_name="source URL",
            ),
        ),
        migrations.AlterField(
            model_name="webmention",
            name="target_url",
            field=models.URLField(
                help_text="Our URL that is mentioned.",
                max_length=500,
                verbose_name="target URL",
            ),
        ),
    ]
