# Generated by Django 4.1.3 on 2022-11-19 17:28

from django.db import migrations, models
import mentions.models.mixins.mentionable


class Migration(migrations.Migration):

    dependencies = [
        ("test_wagtail_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentionablepage",
            name="allow_outgoing_webmentions",
            field=models.BooleanField(
                default=mentions.models.mixins.mentionable._outgoing_default
            ),
        ),
    ]
