# Generated by Django 4.1 on 2022-12-01 15:05

from django.db import migrations, models
import mentions.models.mixins.mentionable


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue47Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_outgoing_webmentions', models.BooleanField(default=mentions.models.mixins.mentionable._outgoing_default, verbose_name='allow outgoing webmentions')),
                ('text', models.TextField(blank=True)),
                ('rss_only', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
