# Generated by Django 4.1 on 2022-10-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_outgoing_webmentions', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
