# Generated by Django 4.1 on 2022-12-01 15:06

from django.db import migrations, models
import mentions.models.mixins.mentionable


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='allow_outgoing_webmentions',
            field=models.BooleanField(default=mentions.models.mixins.mentionable._outgoing_default, verbose_name='allow outgoing webmentions'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='allow_outgoing_webmentions',
            field=models.BooleanField(default=mentions.models.mixins.mentionable._outgoing_default, verbose_name='allow outgoing webmentions'),
        ),
    ]
