name: Tests
on: [push, pull_request]
jobs:
  runtests_nocelery:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.7', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python runtests.py

  runtests_withcelery:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.7', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install celery

    - name: Run tests
      run: |
        python runtests.py

  runtests_withwagtail:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.7', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install wagtail

    - name: Run tests
      run: |
        python runtests.py
