name: Tests
on: [push]
jobs:
  runtests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.ppython-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Run tests with all dependencies.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python runtests.py

    # Uninstall celery and run tests again.
    - name: Uninstall celery
      run: |
        pip uninstall celery -y
    - name: Run tests without celery
      run: |
        python runtests.py
